import {BASE_URL, NODE_ENV, isDevelopment, TOKEN_NAME} from './config';
import {
    EXIST_ERROR,
    EXPIRED_ERROR,
    FORBIDDEN_ERROR,
    HEADER_ERROR,
    NOT_FOUND_ERROR,
    SERVER_ERROR,
    TIMEOUT_ERROR,
    UNAUTHORIZED_ERROR
} from './messages';

export {
    BASE_URL,
    NODE_ENV,
    isDevelopment,
    EXIST_ERROR,
    EXPIRED_ERROR,
    FORBIDDEN_ERROR,
    HEADER_ERROR,
    NOT_FOUND_ERROR,
    SERVER_ERROR,
    TIMEOUT_ERROR,
    UNAUTHORIZED_ERROR,
    TOKEN_NAME
};
